- name: install salt master
  apt:
    name: salt-master
    state: present

- name: copy master file
  template:
    src: master.j2
    dest: /etc/salt/master
  notify:
    - restart master

- name: copy pillar dir master
  ansible.builtin.copy:
    src: srv/pillar/
    dest: /srv/pillar/
    owner: root
    group: root
  notify:
    - sync pillar to minion

- name: copy salt dir to master
  ansible.builtin.copy:
    src: srv/salt/
    dest: /srv/salt/
    owner: root
    group: root
